server:
  port: ${port:80}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cw2m6xryal2i.ap-northeast-2.rds.amazonaws.com/todolist?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: junil
    password: 1q2w3e4r
  
mybatis:
  mapper-locations:
  - /mappers/*.xml
    
      
      